# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sketchingTool.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SketchingTool(object):
    def setupUi(self, SketchingTool):
        SketchingTool.setObjectName("SketchingTool")
        SketchingTool.resize(1095, 844)
        self.centralwidget = QtWidgets.QWidget(SketchingTool)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.picturesForSketch = QtWidgets.QGraphicsView(self.centralwidget)
        self.picturesForSketch.setObjectName("picturesForSketch")
        self.verticalLayout_5.addWidget(self.picturesForSketch)
        spacerItem = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.prevButton = QtWidgets.QPushButton(self.centralwidget)
        self.prevButton.setMinimumSize(QtCore.QSize(20, 20))
        self.prevButton.setMaximumSize(QtCore.QSize(30, 30))
        self.prevButton.setObjectName("prevButton")
        self.horizontalLayout_5.addWidget(self.prevButton)
        self.pictureTime = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pictureTime.sizePolicy().hasHeightForWidth())
        self.pictureTime.setSizePolicy(sizePolicy)
        self.pictureTime.setMinimumSize(QtCore.QSize(30, 30))
        self.pictureTime.setMaximumSize(QtCore.QSize(40, 40))
        self.pictureTime.setObjectName("pictureTime")
        self.horizontalLayout_5.addWidget(self.pictureTime)
        self.nextButton = QtWidgets.QPushButton(self.centralwidget)
        self.nextButton.setMinimumSize(QtCore.QSize(20, 20))
        self.nextButton.setMaximumSize(QtCore.QSize(30, 30))
        self.nextButton.setObjectName("nextButton")
        self.horizontalLayout_5.addWidget(self.nextButton)
        self.verticalLayout_11.addLayout(self.horizontalLayout_5)
        self.playButton = QtWidgets.QPushButton(self.centralwidget)
        self.playButton.setObjectName("playButton")
        self.verticalLayout_11.addWidget(self.playButton)
        self.horizontalLayout_3.addLayout(self.verticalLayout_11)
        spacerItem2 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout.addLayout(self.verticalLayout_5)
        SketchingTool.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SketchingTool)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1095, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuChoose_the_folder = QtWidgets.QMenu(self.menuFile)
        self.menuChoose_the_folder.setObjectName("menuChoose_the_folder")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        SketchingTool.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SketchingTool)
        self.statusbar.setObjectName("statusbar")
        SketchingTool.setStatusBar(self.statusbar)
        self.actionLog_In_Pinterest = QtWidgets.QAction(SketchingTool)
        self.actionLog_In_Pinterest.setObjectName("actionLog_In_Pinterest")
        self.actionLog_In_Google_Photos = QtWidgets.QAction(SketchingTool)
        self.actionLog_In_Google_Photos.setObjectName("actionLog_In_Google_Photos")
        self.actionPinterest = QtWidgets.QAction(SketchingTool)
        self.actionPinterest.setObjectName("actionPinterest")
        self.actionGoogle_Photo = QtWidgets.QAction(SketchingTool)
        self.actionGoogle_Photo.setObjectName("actionGoogle_Photo")
        self.actionLocal = QtWidgets.QAction(SketchingTool)
        self.actionLocal.setObjectName("actionLocal")
        self.menuChoose_the_folder.addAction(self.actionPinterest)
        self.menuChoose_the_folder.addAction(self.actionGoogle_Photo)
        self.menuChoose_the_folder.addAction(self.actionLocal)
        self.menuFile.addAction(self.actionLog_In_Pinterest)
        self.menuFile.addAction(self.actionLog_In_Google_Photos)
        self.menuFile.addAction(self.menuChoose_the_folder.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(SketchingTool)
        QtCore.QMetaObject.connectSlotsByName(SketchingTool)

    def retranslateUi(self, SketchingTool):
        _translate = QtCore.QCoreApplication.translate
        SketchingTool.setWindowTitle(_translate("SketchingTool", "SketchingTool"))
        self.label.setText(_translate("SketchingTool", "Сколько минут будем рисовать?"))
        self.prevButton.setText(_translate("SketchingTool", "<"))
        self.nextButton.setText(_translate("SketchingTool", ">"))
        self.playButton.setText(_translate("SketchingTool", "Рисуем"))
        self.menuFile.setTitle(_translate("SketchingTool", "File"))
        self.menuChoose_the_folder.setTitle(_translate("SketchingTool", "Choose the folder"))
        self.menuHelp.setTitle(_translate("SketchingTool", "Help"))
        self.actionLog_In_Pinterest.setText(_translate("SketchingTool", "Log In Pinterest"))
        self.actionLog_In_Google_Photos.setText(_translate("SketchingTool", "Log In Google Photos"))
        self.actionPinterest.setText(_translate("SketchingTool", "Pinterest"))
        self.actionGoogle_Photo.setText(_translate("SketchingTool", "Google Photo"))
        self.actionLocal.setText(_translate("SketchingTool", "Local"))

